[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["Rupert Rutledge <1982481+Eosis@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.4"
itertools = "0.9.0"
